# Generated by Django 2.2.6 on 2019-10-31 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tgnotes', '0002_auto_20191031_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note', to='tgnotes.Author'),
        ),
    ]
